export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        deptName: 'ZJ省大数据发展管理局',
        taskName: '高等级病原微生物实验室建设审批',
        catalogCode: '990117001000',
        materialCount: '1',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 2,
        deptName: 'ZJ省市场监管局',
        taskName: '烟草专卖零售许可证新办办理',
        catalogCode: '990113001001',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 3,
        deptName: 'ZJ省共青团省委',
        taskName: '共青团省委',
        catalogCode: '990113001002',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 4,
        deptName: 'ZJ省国家保密局',
        taskName: '国家保密局',
        catalogCode: '990113001003',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 5,
        deptName: 'ZJ省版权局',
        taskName: '版权局',
        catalogCode: '990113001004',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 6,
        deptName: 'ZJ省残疾人联合会',
        taskName: '残疾人联合会',
        catalogCode: '990113001005',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 7,
        deptName: 'ZJ省财政厅',
        taskName: '财政厅',
        catalogCode: '990113001006',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 8,
        deptName: 'ZJ省档案局',
        taskName: '档案局',
        catalogCode: '990113001007',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 9,
        deptName: 'ZJ省市场监督管理局',
        taskName: '监督管理局',
        catalogCode: '990113001008',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
      {
        id: 10,
        deptName: 'ZJ省自然资源厅',
        taskName: '自然资源厅',
        catalogCode: '990113001009',
        materialCount: '0',
        isChecked: '0',
        typeKey: ["1", "3"],
        useLevelList: ["1"],
      },
    ],
    total: 2,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData2 = {
  code: 0,
  data: {
    records: [{
      id: 1,
      materialName: '法定代表人身份证',
      itemName: '身份证号码',
    }],
    total: 2,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
