export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        dataDeptName: '省办公厅',
        dataTableName: '政务服务事项目录清单',
        dataFieldName: '地方基本编码',
        cleanState: '2',
      },
      {
        id: 2,
        dataDeptName: '浙江省政府部门',
        dataTableName: '许可、给付、奖励、确认、其他类事项、公共服务事项要素规范-基本信息',
        dataFieldName: '实施主体',
        cleanState: '1',
      },
      {
        id: 3,
        dataDeptName: '省办公厅',
        dataTableName: '政务服务事项目录清单',
        dataFieldName: '事项名称',
        cleanState: '0',
      },
      {
        id: 4,
        dataDeptName: '省办公厅',
        dataTableName: '政务服务事项目录清单',
        dataFieldName: '基本编码',
        cleanState: '1',
      },
      {
        id: 5,
        dataDeptName: '省教育厅',
        dataTableName: '学生信息表',
        dataFieldName: '业务办理项编码',
        cleanState: '0',
      },
      {
        id: 6,
        dataDeptName: '省教育厅',
        dataTableName: '学生信息表',
        dataFieldName: '批次号',
        cleanState: '1',
      },
      {
        id: 7,
        dataDeptName: '省办公厅',
        dataTableName: '学生信息表',
        dataFieldName: '监督投诉方式',
        cleanState: '0',
      },
      {
        id: 8,
        dataDeptName: '浙江省政府部门',
        dataTableName: '学生信息表',
        dataFieldName: '受理条件',
        cleanState: '1',
      },
      {
        id: 9,
        dataDeptName: '省办公厅',
        dataTableName: '学生信息表',
        dataFieldName: '事项状态',
        cleanState: '0',
      },
      {
        id: 10,
        dataDeptName: '浙江省政府部门',
        dataTableName: '学生信息表',
        dataFieldName: '行使层级',
        cleanState: '1',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData2 = {
  code: 0,
  data: {
    records: [{
      id: 1,
      ruleNumber: 'GZ000000223',
      ruleName: '高等学校本科、专科专业名称代码',
      ruleNameEn: 'Code of normal and short-cycle speciallty',
      cleanScope: '无限制',
      cleanSort: '1',
    }],
    total: 1,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData3 = {
  code: 0,
  data: {
    records: [{
        id: 1,
        sourceData: '省应急管理厅',
        cleanResult: '不符合规则',
      },
      {
        id: 2,
        sourceData: '省应急管理厅',
        cleanResult: '不符合规则',
      },
    ],
    total: 2,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
