stages:
  - build
  - deploy-release
  - deploy-master

cache:
  key: ${CI_COMMIT_REF_NAME}
  paths:
    - node_modules/

build_master_job:
  image: node:14.15.3
  stage: build
  tags:
    - ivhik
  only:
    - deploy-master
  script:
    - yarn install --frozen-lockfile
    - yarn staging
  artifacts:
    name: "ican-ui-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist

build_release_job:
  image: node:14.15.3
  stage: build
  tags:
    - ivhik
  only:
    - deploy-release
  script:
    - yarn install --frozen-lockfile
    - yarn build
  artifacts:
    name: "ican-ui-$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHA"
    expire_in: 1 week
    paths:
      - dist

deploy_release_job:
  image: alpine
  stage: deploy-release
  only:
    - deploy-release
  tags:
    - ivhik
  script:
    - echo "http://mirrors.aliyun.com/alpine/v3.8/main/" > /etc/apk/repositories
    - apk add --no-cache rsync openssh
    # curl unzip
    # - 'curl --location --output artifacts.zip --header "JOB-TOKEN: $CI_JOB_TOKEN" "https://gitlab.ivhik.cn/frontend/ican-ui/-/jobs/artifacts/master/download?job=build_job"'
    # - unzip -q artifacts.zip
    # - rm -rf artifacts.zip
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host $DEPLOY_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - rsync -rav -e "ssh -p $DEPLOY_PORT" --delete dist/ "$DEPLOY_SERVER:$SERVER_DEV_PATH_WONENG"

deploy_master_job:
  image: alpine
  stage: deploy-master
  only:
    - deploy-master
  tags:
    - ivhik
  script:
    - echo "http://mirrors.aliyun.com/alpine/v3.8/main/" > /etc/apk/repositories
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host $DEPLOY_SERVER_MASTER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
    - rsync -rav -e "ssh -p $DEPLOY_PORT_MASTER" --delete dist/ "$DEPLOY_SERVER_MASTER:$SERVER_DEV_PATH_WONENG"
