export const matterData = [{
    type: "全部",
  },
  {
    type: "表格类（17）",
  },
  {
    type: "证明类（0）",
  },
  {
    type: "批文类（0）",
  },
  {
    type: "证照类（1）",
  },
  {
    type: "其它类（1）",
  },
];

export const mockData = {
  code: 0,
  data: {
    records: [{
        val1: "项目验收材料",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "安全生产检测检验机构资质认定申请表",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "安全生产许可证变更申请书",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "工商营业执照复印件",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "变更申请书",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "申请经营许可证延期文件及延期申请书",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "变更说明材料",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "变更后主要负责人的安全合格证",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "批发许可证延期申请书",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
      {
        val1: "批发许可证变更申请书",
        val2: "1",
        val3: "1",
        val4: "1",
        val5: [],
        val6: [],
        val7: "",
        val8: "",
        val9: "",
        val10: "",
        val11: "",
        val12: "",
        val13: "",
      },
    ],
    total: 1,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
