export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '中职毕业证信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '全国中等职业学校学生管理信息系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 2,
        commonDataMetaName: '全州中等职业教育阶段学生信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '全国中等职业学校学生管理信息系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 4,
        commonDataMetaName: '中小企业股权新三板交易信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '中小企业股权新三板交易信息系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 5,
        commonDataMetaName: '公积金提取审批信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '湘西自治州公积金业务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 6,
        commonDataMetaName: '湘西州小额贷款公司合规经营自查信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '小额贷款公司监测管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 7,
        commonDataMetaName: '全州中职学校（机构）信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '全国中等职业学校学生管理信息系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 8,
        commonDataMetaName: '小额贷款公司贷款情况汇总表（月报）',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '小额贷款公司监测管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 9,
        commonDataMetaName: '小额贷款公司机构信息',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '小额贷款公司监测管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 10,
        commonDataMetaName: '私募股权基金监管',
        commonDataMetaNameEn: '州教体局',
        commonDataMetaNumber: '省资本市场信息管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
