export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName: '餐饮业',
      num: '04',
      content: '餐饮业消费',
    }, {
      id: 1,
      commonDataMetaName: '服务业',
      num: '04',
      content: '服务业消费',
    }, {
      id: 2,
      commonDataMetaName: '旅游业',
      num: '04',
      content: '旅游业消费',
    }, {
      id: 3,
      commonDataMetaName: '出行',
      num: '04',
      content: '出行消费',
    }, {
      id: 4,
      commonDataMetaName: '动车',
      num: '04',
      content: '动车消费',
    }, {
      id: 5,
      commonDataMetaName: '公交',
      num: '04',
      content: '公交消费',
    }, {
      id: 6,
      commonDataMetaName: '监管业',
      num: '04',
      content: '监管业消费',
    }, {
      id: 7,
      commonDataMetaName: '管理业',
      num: '04',
      content: '管理业消费',
    }, {
      id: 8,
      commonDataMetaName: '维护',
      num: '04',
      content: '维护消费',
    }, {
      id: 10,
      commonDataMetaName: '其他',
      num: '06',
      content: '其他很多行业',
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
