export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        dbCn: '中文库',
        dbEn: 'chinese',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 2,
        dbCn: '人口库',
        dbEn: 'RKK',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 3,
        dbCn: '法人库',
        dbEn: 'FRK',
        dbType: '1',
        dbNotes: '',
      },
      {
        id: 1,
        dbCn: '材料库',
        dbEn: 'chinese',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 2,
        dbCn: '申请库',
        dbEn: 'RKK',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 3,
        dbCn: '提交库',
        dbEn: 'FRK',
        dbType: '1',
        dbNotes: '',
      },
      {
        id: 1,
        dbCn: '人员信息登记库',
        dbEn: 'chinese',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 2,
        dbCn: '车辆登记库',
        dbEn: 'RKK',
        dbType: '3',
        dbNotes: '',
      },
      {
        id: 3,
        dbCn: '考勤库',
        dbEn: 'FRK',
        dbType: '1',
        dbNotes: '',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData2 = {
  code: 0,
  data: {
    records: [{
        id: 1,
        tableCn: '测试毕业生登记信息表',
        tableEn: 'abc',
        tableType: '3',
        modelBuildIds: '法人库，人口库',
        tableNotes: '',
      },
      {
        id: 2,
        tableCn: '毕业生登记信息表',
        tableEn: 'BYSDJXXB',
        tableType: '1',
        modelBuildIds: '学生信息库，法人库，人口库',
        tableNotes: '',
      },
      {
        id: 3,
        tableCn: '法人单位信息登记表',
        tableEn: 'FRDWXXDJB',
        tableType: '2',
        modelBuildIds: '法人库，人口库',
        tableNotes: '',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
