export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        projectNo: 'NB-81-28-32',
        projectType: '新建',
        yearStart: '2020',
        projectName: '20200108DNA项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 2,
        projectNo: 'NB-81-85-32',
        projectType: '新建',
        yearStart: '2020',
        projectName: '测试项20200108山东项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 3,
        projectNo: 'NB-76-59-65',
        projectType: '对接',
        yearStart: '2020',
        projectName: '20200108淘鱼吧项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 4,
        projectNo: 'NB-84-88-68',
        projectType: '对接',
        yearStart: '2020',
        projectName: '20200108DNA项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 5,
        projectNo: 'NB-81-59-32',
        projectType: '二次开发',
        yearStart: '2020',
        projectName: '20200108淘鱼吧项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 6,
        projectNo: 'NB-64-64-23',
        projectType: '二次开发',
        yearStart: '2020',
        projectName: '20200111四川项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 7,
        projectNo: 'NB-33-55-61',
        projectType: '新建',
        yearStart: '2020',
        projectName: '20200110湖南项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 8,
        projectNo: 'NB-81-59-32',
        projectType: '新建',
        yearStart: '2020',
        projectName: '20200108山东项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
      {
        id: 9,
        projectNo: 'NB-23-34-32',
        projectType: '新建',
        yearStart: '2020',
        projectName: '20200108淘鱼吧项目',
        deptName: '省政府',
        fundType: '部门预算',
        currentState: '汇总不通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
