export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName1: 'ZJ省',
      commonDataMetaName2: 'ZJ省大数据发展管理局',
      commonDataMetaName3: '全省大数据管理系统',
      commonDataMetaName4: '待审核',
      commonDataMetaName: '全省大数据管理系统',
      commonDataMetaNameEn: '2',
      commonDataMetaNumber: '10000',
      commonDataMetaValue: '100000',
      govStandardDocumentsId: '审核通过',
      address: '183.131.134.242',
      Affiliated: 'HZ市教育局',
      department: '市教育局',
      ApprovalDate: '2020-03-02',
      BudgetItemName: ' ',
      budget: ' ',
      endBudget: ' ',
      corpse: 1,
      startDate: '2020-03-10',
      serviceDate: '2020-03-31',
      status: '运行中',
      Source: '上级配套',
      SourceFunds: '全省统一云平台',
      environment: '互联网',
      ScopeOfUse: '地市',
      ScopeOfUseUser: '本部门本级',
      frequency: '100',
      frequencyUse: '系统日志',
      DataGeneration: '省市县逐级报送',
      dataUpload: '按天',
      DatabaseFormat: 'MSSQL',
      DataSize: '10000',
      DataNum: '100000',
      Growth: '1000',
      stockData: '10',
      DataValidity: '10',
      dict: 1,
      position: ' ',
      Sharing: '内设机构内部',
      GradeProtection: '二级',
      Centralized: '市教育局',
      ContactPerson: '王慧君',
      ContactPhone: '1369871420',
      Person: '王珮',
      PersonPhone: '1369781120',
      maintenance: '何提宇',
      maintenancePhone: '13694203697',
      developmentTime: '2020-03-17',
      Manufacturer: '华为',
      ManufacturerPerson: '叶嘉丽',
      ManufacturerPhone: '136921400',
      content: '',
      ServiceIntroduction: '',
      other: 1,
      isYw: 1,
      pagedTable: [],
      pagedTable1: [{
        commonDataMetaName: '中小学学生信息',
        commonDataMetaNameEn: '电子表格 | xlsx',
        commonDataMetaNameEn1: '无条件共享',
        commonDataMetaNameEn2: '否',
      }, {
        commonDataMetaName: '学生家长登记信息',
        commonDataMetaNameEn: '电子表格 | xlsx',
        commonDataMetaNameEn1: '有条件共享',
        commonDataMetaNameEn2: '否',
      }],
      pagedTable2: [{
        commonDataMetaName: 'v1',
        commonDataMetaNameEn: '2020-03-21 23:09:49',
        commonDataMetaNameEn1: 'admin',
      }],
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
