export const selectData = [{
  name: "单选题",
  type: "1",
  optionList: [],
  icon: "icon-yuan1",
  isRequire: "1",
  isShow: "1",
  logic: {},
  isPicTitle: "0",
  answer: {},
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你最喜欢的水果是什么？",
    answer: {},
  },
}, {
  name: "多选题",
  icon: "icon-piliang-copy",
  optionList: [],
  isRequire: "1",
  isShow: "1",
  type: "2",
  logic: {},
  minNum: 0,
  maxNum: 0,
  isPicTitle: "0",
  answer: {
    value: [],
    optionId: "",
  },
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你喜欢哪些水果？",
    optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
    answer: { value: [] },
  },
}, {
  name: "图片单选",
  icon: "icon-mulu4",
  optionList: [],
  isRequire: "1",
  isShow: "1",
  type: "3",
  logic: {},
  isPicTitle: "0",
  answer: {
    values: [],
  },
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你最喜欢哪个图片",
    optionList: [{ name: "{}", description: "香蕉" }, { name: "{}", description: "橘子" }, { name: "{}", description: "苹果" }],
    answer: { values: [] },
  },
}, {
  name: "图片多选",
  icon: "icon-daibanshixiang",
  optionList: [],
  isRequire: "1",
  isShow: "1",
  type: "4",
  logic: {},
  minNum: 0,
  maxNum: 0,
  isPicTitle: "0",
  answer: {
    values: [],
  },
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你喜欢哪些图片",
    optionList: [{ name: "{}", description: "香蕉" }, { name: "{}", description: "橘子" }, { name: "{}", description: "苹果" }],
    answer: { values: [] },
  },
}, {
  name: "下拉题",
  icon: "icon-mulu1",
  optionList: [],
  type: "5",
  isRequire: "1",
  isShow: "1",
  logic: {},
  isPicTitle: "0",
  answer: {},
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你喜欢哪个水果？",
    optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
    answer: {},
  },
}];

export const inputData = [{
  optionList: [],
  name: "填空题",
  icon: "icon-shuben-zhuanye",
  type: "6",
  isRequire: "1",
  isShow: "1",
  logic: {},
  isPicTitle: "0",
  answer: {},
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你喜欢哪些水果？",
    optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
    answer: {},
  },
}, {
  optionList: [],
  name: "多项填空",
  icon: "icon-task",
  type: "7",
  isRequire: "1",
  isShow: "1",
  logic: {},
  isPicTitle: "0",
  answer: {},
  example: {
    isPicTitle: "0",
    isShow: "1",
    title: "你喜欢哪些水果？",
    optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
    answer: { value: "" },
  },
}];

export const otherData = [
  {
    name: "打分题",
    icon: "icon-pingfen",
    optionList: [],
    type: "8",
    isRequire: "1",
    isShow: "1",
    logic: {},
    isPicTitle: "0",
    answer: {},
    example: {
      isPicTitle: "0",
      isShow: "1",
      title: "你给这些水果打几星？",
      optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
      answer: {},
    },
  },
  {
    name: "上传题",
    icon: "icon-cz-quxiaochehui",
    optionList: [],
    type: "9",
    isRequire: "1",
    isShow: "1",
    logic: {},
    isPicTitle: "0",
    answer: {
      fileList: [],
    },
    example: {
      isPicTitle: "0",
      isShow: "1",
      title: "上传文件",
      optionList: [{ name: "香蕉" }, { name: "橘子" }, { name: "苹果" }, { name: "西瓜" }],
      answer: {
        fileList: [],
      },
    },
  },
  {
    name: "备注说明",
    icon: "icon-cz-wenjianzc",
    optionList: [],
    isRequire: "2",
    isShow: "1",
    remarks: "",
    type: "10",
    logic: {},
    answer: {
      value: "",
    },
    example: {
      isShow: "1",
      title: "这是备注内容",
      answer: {
        value: "",
      },
    },
  },
];