export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        tableCn: '测试毕业生登记信息表',
        tableEn: 'abc',
        tableType: '3',
        modelBuildIds: '法人库，人口库',
        tableNotes: '',
      },
      {
        id: 2,
        tableCn: '毕业生登记信息表',
        tableEn: 'BYSDJXXB',
        tableType: '1',
        modelBuildIds: '学生信息库，法人库，人口库',
        tableNotes: '',
      },
      {
        id: 3,
        tableCn: '法人单位信息登记表',
        tableEn: 'FRDWXXDJB',
        tableType: '2',
        modelBuildIds: '法人库，人口库',
        tableNotes: '',
      },
      {
        id: 1,
        tableCn: '刑满释放人员安置帮教情况统计表',
        tableEn: 'abc',
        tableType: '3',
        modelBuildIds: '服刑人员表现查询信息库',
        tableNotes: '',
      },
      {
        id: 2,
        tableCn: '服刑人员表现查询信息表',
        tableEn: 'BYSDJXXB',
        tableType: '1',
        modelBuildIds: '服刑人员表现查询信息库',
        tableNotes: '',
      },
      {
        id: 3,
        tableCn: '社区矫正安全监管警报警告信息表',
        tableEn: 'FRDWXXDJB',
        tableType: '2',
        modelBuildIds: '社区矫正安全监管警报警告信息库',
        tableNotes: '',
      },
      {
        id: 1,
        tableCn: '社区矫正安全监管异常统计信息表',
        tableEn: 'abc',
        tableType: '3',
        modelBuildIds: '社区矫正安全监管异常统计信息库',
        tableNotes: '',
      },
      {
        id: 2,
        tableCn: '解矫人员名册表',
        tableEn: 'BYSDJXXB',
        tableType: '1',
        modelBuildIds: '解矫人员名册库',
        tableNotes: '',
      },
      {
        id: 3,
        tableCn: '解除矫正期满鉴定信息表',
        tableEn: 'FRDWXXDJB',
        tableType: '2',
        modelBuildIds: '解除矫正期满鉴定信息库',
        tableNotes: '',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData2 = {
  code: 0,
  data: {
    records: [{
        id: 1,
        dataCn: '农田灌溉水质要求',
        dataEn: '无',
        dataType: '1',
        isPrimaryKey: '2',
        isNull: '2',
      },
      {
        id: 2,
        dataCn: '土壤肥力要求',
        dataEn: '无',
        dataType: '2',
        isPrimaryKey: '2',
        isNull: '2',
      },
      {
        id: 3,
        dataCn: '土壤坏境质量要求',
        dataEn: '无',
        dataType: '3',
        isPrimaryKey: '2',
        isNull: '2',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
