export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '湖南省建设企业管理信息系统',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '王晓红',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '湖南省建筑业诚信信息管理系统',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '王晓红',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '湖南省城镇燃气管理信息系统',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '张算哲',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '湖南省建筑工程项目管理系统',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '罗平城',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '全国建筑市场监管公共服务平台',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '朱子菊',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '成都基础建设管理',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '王晓红',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '全国建筑市场监管公共服务平台',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '关晓松',
        uploadState: '已上报',
      },
      {
        id: 1,
        projectNo: 'BJ-12312-1',
        projectYearNo: 'YH-ASDFADF-13',
        projectName: '湖南省建筑工程项目管理系统',
        deptName: '省政府',
        budgetType: '市预算',
        financialAuditFund: 123,
        projectApprovalFund: 100,
        projectLeader: '李小芳',
        uploadState: '已上报',
      },

    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
