export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName: '31',
      commonDataMetaName1: ' ',
      commonDataMetaName2: ' ',
      commonDataMetaName3: ' ',
      commonDataMetaName4: ' ',
      commonDataMetaName5: '0',
      commonDataMetaName6: '上海市',
      children: [{
        id: 2,
        commonDataMetaName: ' ',
        commonDataMetaName1: '01',
        commonDataMetaName2: ' ',
        commonDataMetaName3: ' ',
        commonDataMetaName4: ' ',
        commonDataMetaName5: '0',
        commonDataMetaName6: '市辖区',
        children: [{
          id: 3,
          commonDataMetaName: ' ',
          commonDataMetaName1: ' ',
          commonDataMetaName2: '01',
          commonDataMetaName3: ' ',
          commonDataMetaName4: ' ',
          commonDataMetaName5: '0',
          commonDataMetaName6: '黄浦区',
          children: [{
            id: 4,
            commonDataMetaName: ' ',
            commonDataMetaName1: ' ',
            commonDataMetaName2: ' ',
            commonDataMetaName3: '002',
            commonDataMetaName4: ' ',
            commonDataMetaName5: '0',
            commonDataMetaName6: '南京东路街道',
            children: [{
              id: 5,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '001',
              commonDataMetaName5: '0',
              commonDataMetaName6: '云南中路居委会',
            }, {
              id: 6,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '002',
              commonDataMetaName5: '0',
              commonDataMetaName6: '龙泉园路居委会',
            }, {
              id: 7,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '003',
              commonDataMetaName5: '0',
              commonDataMetaName6: '贵州路居委会',
            }, {
              id: 8,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '006',
              commonDataMetaName5: '0',
              commonDataMetaName6: '新桥居委会',
            }, {
              id: 9,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '007',
              commonDataMetaName5: '0',
              commonDataMetaName6: '牛庄路居委会',
            }],
          }],
        }],
      }],
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
