export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 14',
        terminology: '辐射噪声',
        terminologyEn: 'radiation noise',
        define: '充电器传播并发射到空间的高频噪声。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 2,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 13',
        terminology: '传导噪声',
        terminologyEn: 'conduction noise',
        define: '重叠或侵入充电器输入或输出端接线的高频噪声。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 3,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: '高频噪声',
        terminologyEn: 'high frequency noise',
        define: '由充电器发出的传导性及辐射性噪声。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 4,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: '谐波电流',
        terminologyEn: 'harmonic current',
        define: ' 与基本频率以外成整数倍的电流的总称。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 5,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: '  凯波电流',
        terminologyEn: 'harmonic current',
        define: ' 与基本频率以外成整数倍的电流的总称。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 6,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: '电流脉动',
        terminologyEn: 'current ripple',
        define: '  叠加在直流电流上的脉动电流。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 7,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4.8',
        terminology: '电压变动范围',
        terminologyEn: 'voltage alteration range',
        define: ' 充电器的交流输人电源电压的允许变动范围，（恒压充电）直流愉出电压的变动范围。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 8,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: ' 电压调节范围',
        terminologyEn: ' voltage adjustable range',
        define: ' 充电器输出电压的可调整范围。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 9,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: ' 效率 ',
        terminologyEn: 'efficiency',
        define: '  输出与输人能量之比。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
      {
        id: 10,
        indexFirst: '3.4',
        classificationFirst: '电动汽车充电器',
        indexSecond: '3.4.4',
        classificationSecond: '蓄电池规格、性能  ',
        indexThird: '',
        classificationThird: '',
        orderNumber: '3.4.4. 12',
        terminology: '冲击电流',
        terminologyEn: 'rush current',
        define: '  充电器起动时在1至数个周期内产生的过大交流（输入）电流，一般用峰值表示。',
        name: ' 电动车术语（2004版）',
        number: 'GB/T 19596',
        version: '2004版',
        icsCodeFirst: 'ICS 43. 020',
        ccsCodeFirst: 'T 04',
        pubAgency: '中华人民共和国国家质量监督检验检疫总局、中国国家标准化管理委员会',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
