export const SET_CONVERSATION_LIST = "SET_CONVERSATION_LIST";
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";
export const SET_MESSAGE_LIST = "SET_MESSAGE_LIST";
export const SET_MESSAGE_HAS_MORE = "SET_MESSAGE_HAS_MORE";
export const SET_USER_INFO_MAP = "SET_USER_INFO_MAP";
export const SET_CURRENT_NEW_MESSAGE = "SET_CURRENT_NEW_MESSAGE";
export const SET_CURRENT = "SET_CURRENT";
export const SET_CUSTOM_MSG_PAGE = "SET_CUSTOM_MSG_PAGE";
export const SET_IS_CUSTOM = "SET_IS_CUSTOM";
export const SET_MESSAGE_TYPE = "SET_MESSAGE_TYPE";
export const SET_MSG_LOADING = "SET_MSG_LOADING";
export const SET_DIALOGSHOW = "SET_DIALOGSHOW";
export const SET_TOTALUNREADCOUNT = "SET_TOTALUNREADCOUNT";
export const SET_EMOJILIST = "SET_EMOJILIST";
export const SET_NOTIFYFLAG = "SET_NOTIFYFLAG";
export const SET_RONGIM_DISABLE = "SET_RONGIM_DISABLE";
export const SET_MESSAGE_CONTENT = "SET_MESSAGE_CONTENT";


