export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        name: '公共数据元数据流转',
        dectipt: '公共数据元数据流转',
        dept: '市政局',
      },
      {
        id: 2,
        name: '信息资源数据流程',
        dectipt: '信息资源数据流程',
        dept: '市教育局',
      },
      {
        id: 3,
        name: '指标评估流程',
        dectipt: '指标评估流程',
        dept: '市政局',
      },
      {
        id: 4,
        name: '运营监督数据流转',
        dectipt: '运营监督数据流转',
        dept: '市政局',
      },
      {
        id: 5,
        name: '项目列表数据流程',
        dectipt: '项目列表数据流程',
        dept: '市教育局',
      },
      {
        id: 6,
        name: '能力升级流程',
        dectipt: '能力升级流程',
        dept: '市政局',
      },
      {
        id: 7,
        name: '区块链数据流转',
        dectipt: '区块链数据流转',
        dept: '市政局',
      },
      {
        id: 8,
        name: '在线建模数据流程',
        dectipt: '在线建模数据流程',
        dept: '市教育局',
      },
      {
        id: 9,
        name: '数据超市流程',
        dectipt: '数据超市流程',
        dept: '市政局',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
