export const mockData = {
  code: 0,
  data: {
    records: [{
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:42:26",
      createUser: 0,
      degree: "3",
      delFlag: 0,
      deptId: 977,
      deptName: "ZS市教育局",
      fileIds: "[]",
      headName: "叶佳良",
      id: 53,
      modifiedTime: "2020-03-20 17:42:26",
      modifiedUser: 0,
      mold: "1",
      name: "ZS市文明校园测评细则数据",
      remarks: "",
      status: "2",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:41:18",
      createUser: 0,
      degree: "3",
      delFlag: 0,
      deptId: 980,
      deptName: "ZS市交通运输局",
      fileIds: "[]",
      headName: "叶佳良",
      id: 52,
      modifiedTime: "2020-03-20 17:41:18",
      modifiedUser: 0,
      mold: "1",
      name: "ZS市交通运输工具（船舶）申报信息数据",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "HZ市经济犯罪案件数据",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对安全评价检测检验机构的监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对生产、经营非药品类易制毒化学品的监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对食品生产企业安全生产的监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对非煤矿山外包工程的安全生产监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对工贸企业有限空间作业的监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }, {
      address: "",
      annexIds: "[]",
      createTime: "2020-03-20 17:40:21",
      createUser: 0,
      degree: "2",
      delFlag: 0,
      deptId: 970,
      deptName: "HZ市公安局",
      fileIds: "[]",
      headName: "钟乙乔",
      id: 51,
      modifiedTime: "2020-03-20 17:40:21",
      modifiedUser: 0,
      mold: "3",
      name: "对危险化学品登记情况的监督检查",
      remarks: "",
      status: "1",
      tenantId: 43,
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
