export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '学生家长登记信息',
        commonDataMetaNameEn: '有条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '文件未注册',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 2,
        commonDataMetaName: '中小学学生信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 3,
        commonDataMetaName: '公积金贷款审批信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 4,
        commonDataMetaName: '公积金提取审批信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 5,
        commonDataMetaName: '湘西州小额贷款公司合规经营自查信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 6,
        commonDataMetaName: '小额贷款公司贷款情况汇总表（月报）',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 7,
        commonDataMetaName: '小额贷款公司机构信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },
      {
        id: 8,
        commonDataMetaName: '私募股权基金管理机构监管信息',
        commonDataMetaNameEn: '无条件',
        commonDataMetaNumber: 'HZ市教育局',
        commonDataMetaValue: '待审核',
        govStandardDocumentsId: '审核通过',
        content: ' ',
      },

    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
