export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: 'ZS市交通运输局',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: '全市交通运输管理系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省公安厅',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省指纹比对系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省教育局',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省中小学生招生系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省教育局',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省普通高中招生系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省应急管理厅',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省应急事件登记系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省应急管理厅',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省工作人员考勤系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省保密局',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省事项登记系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省档案局',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省档案录入系统',
        govStandardDocumentsId: 'MYSQL',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省财政厅',
        commonDataMetaNameEn: 'gds_data_matrix',
        commonDataMetaNumber: 'gds_data_matrix',
        commonDataMetaValue: 'ZJ省指财政录入系统',
        govStandardDocumentsId: 'MYSQL',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
