export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName: 'GZ000000298',
      commonDataMetaNameEn: '国籍代码',
      commonDataMetaNumber: 'Nationality Code',
      commonDataMetaValue: '世界各国和地区名称代码(2000版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'GB/T 2659',
      versionNo: '2000版',
      ics: 'ICS 01.040.03',
      css: 'A 24',
      issuedBy: '国家质量技术监督局',
      pagedTable: [{
          commonDataMetaName: 'ABW',
          commonDataMetaNameEn: '阿鲁巴',
        },
        {
          commonDataMetaName: 'AFG',
          commonDataMetaNameEn: '阿富汗',
        },
        {
          commonDataMetaName: 'AGO',
          commonDataMetaNameEn: '安哥拉',
        },
        {
          commonDataMetaName: 'AIA',
          commonDataMetaNameEn: '安圭拉',
        },
        {
          commonDataMetaName: 'ALB',
          commonDataMetaNameEn: '阿尔巴尼亚',
        },
        {
          commonDataMetaName: 'AND',
          commonDataMetaNameEn: '安道尔',
        },
      ],
    }, {
      id: 1,
      commonDataMetaName: 'GZ000000297',
      commonDataMetaNameEn: '服务主题分类代码',
      commonDataMetaNumber: 'Service Subject Classification Code',
      commonDataMetaValue: '政务服务平台 第6部分：事项分类(2019版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'DB37/T 3448.6',
      versionNo: '2019版',
      ics: 'ICS 35.240.01',
      css: 'L 70',
      issuedBy: '省市场监督管理局',
      pagedTable: [{
          commonDataMetaName: 'D101',
          commonDataMetaNameEn: '生育收养',
        },
        {
          commonDataMetaName: 'D102',
          commonDataMetaNameEn: 'D102',
        },
        {
          commonDataMetaName: 'D103',
          commonDataMetaNameEn: '民族宗教',
        },
        {
          commonDataMetaName: 'D104',
          commonDataMetaNameEn: '教育科研',
        },
        {
          commonDataMetaName: 'D105',
          commonDataMetaNameEn: '入伍服役',
        },
        {
          commonDataMetaName: 'D106',
          commonDataMetaNameEn: '就业创业',
        },
      ],
    }, {
      id: 20,
      commonDataMetaName: 'GZ000000397',
      commonDataMetaNameEn: '行政管辖分类代码',
      commonDataMetaNumber: 'Administrative Jurisdiction Classification Code',
      commonDataMetaValue: '政务服务平台 第6部分：事项分类(2019版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'DB37/T 3448.6',
      versionNo: '2019版',
      ics: 'ICS 35.240.01',
      css: 'L 70',
      issuedBy: '省市场监督管理局',
      pagedTable: [{
          commonDataMetaName: 'G1',
          commonDataMetaNameEn: '定点管理',
        },
        {
          commonDataMetaName: 'G2',
          commonDataMetaNameEn: '跨地区通办',
        },
      ],
    }, {
      id: 21,
      commonDataMetaName: 'GZ000000497',
      commonDataMetaNameEn: '服务形式分类代码',
      commonDataMetaNumber: 'Service Form Classification Code',
      commonDataMetaValue: '政务服务平台 第6部分：事项分类(2019版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'DB37/T 3448.6',
      versionNo: '2019版',
      ics: 'ICS 35.240.01',
      css: 'L 70',
      issuedBy: '省市场监督管理局',
      pagedTable: [{
          commonDataMetaName: 'F1',
          commonDataMetaNameEn: '线上办理',
        },
        {
          commonDataMetaName: 'F2',
          commonDataMetaNameEn: '线下办理',
        },
        {
          commonDataMetaName: 'F3',
          commonDataMetaNameEn: '线上线下一体化办理',
        },
      ],
    }, {
      id: 22,
      commonDataMetaName: 'GZ000000997',
      commonDataMetaNameEn: '服务层级分类代码',
      commonDataMetaNumber: 'Service level classification code',
      commonDataMetaValue: '政务服务平台 第6部分：事项分类(2019版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'DB37/T 3448.6',
      versionNo: '2019版',
      ics: 'ICS 35.240.01',
      css: 'L 70',
      issuedBy: '省市场监督管理局',
      pagedTable: [{
          commonDataMetaName: 'E1',
          commonDataMetaNameEn: '省级',
        },
        {
          commonDataMetaName: 'E2',
          commonDataMetaNameEn: '市级',
        },
        {
          commonDataMetaName: 'E3',
          commonDataMetaNameEn: '县（市、区）级',
        },
        {
          commonDataMetaName: 'E4',
          commonDataMetaNameEn: '乡镇（街道）级',
        },
        {
          commonDataMetaName: 'E5S',
          commonDataMetaNameEn: '村居（社区）级（代办）',
        },
      ],
    }, {
      id: 23,
      commonDataMetaName: 'GZ000001997',
      commonDataMetaNameEn: '事项分类方式代码',
      commonDataMetaNumber: 'Item Classification Code',
      commonDataMetaValue: '政务服务平台 第6部分：事项分类(2019版)',
      standardDocuments: '',
      belongingData: '世界各国和地区名称代码(2000版)',
      StandardNo: 'DB37/T 3448.6',
      versionNo: '2019版',
      ics: 'ICS 35.240.01',
      css: 'L 70',
      issuedBy: '省市场监督管理局',
      pagedTable: [{
          commonDataMetaName: 'A',
          commonDataMetaNameEn: '事项性质',
        },
        {
          commonDataMetaName: 'B',
          commonDataMetaNameEn: '服务对象',
        },
        {
          commonDataMetaName: 'C',
          commonDataMetaNameEn: '实施主体',
        },
        {
          commonDataMetaName: 'D',
          commonDataMetaNameEn: '服务主题',
        },
        {
          commonDataMetaName: 'E',
          commonDataMetaNameEn: '服务层级',
        },
      ],
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
