export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '上市后备企业申报-财务状况',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '省资本市场信息管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 2,
        commonDataMetaName: '上市后备企业申报-股本结构',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '省资本市场信息管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 3,
        commonDataMetaName: '上市后备企业申报-企业基本信息',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '省资本市场信息管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 4,
        commonDataMetaName: '融资担保公司风险预警',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 5,
        commonDataMetaName: '融资担保公司年度、季度、月度报表-准备金提取情况',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 6,
        commonDataMetaName: '融资担保公司年度、季度、月度报表-代偿与损失统计',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 7,
        commonDataMetaName: '融资担保公司年度、季度、月度报表-行业担保情况',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 8,
        commonDataMetaName: '融资担保公司年度、季度、月度报表-累计担保情况',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 9,
        commonDataMetaName: '融资担保公司年度、季度、月度报表-落实产业政策情况',
        commonDataMetaNameEn: '州人民政府办公室',
        commonDataMetaNumber: '融资性担保机构监管预警系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
