export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '票价调整信息',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '州信用信息共享交换平台',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 2,
        commonDataMetaName: '价格违法行为处罚信息',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '州信用信息共享交换平台',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 3,
        commonDataMetaName: '专利侵权纠纷处理请求立案通知书',
        commonDataMetaNameEn: '州科技局',
        commonDataMetaNumber: '州信用信息共享交换平台',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 4,
        commonDataMetaName: '宗教团体筹备信息',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 5,
        commonDataMetaName: '州级宗教团体负责人信息',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 6,
        commonDataMetaName: '可以进行集体宗教活动的场合的认可信息',
        commonDataMetaNameEn: '州科技局',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 7,
        commonDataMetaName: '宗教团体和寺观教堂举办宗教教职人员培训审批表',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 8,
        commonDataMetaName: '收集登记湘西州宗教工作机构信息',
        commonDataMetaNameEn: '州发改委',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 9,
        commonDataMetaName: '收集登记湘西州宗教院校信息',
        commonDataMetaNameEn: '州科技局',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
