export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '湘西州排污许可证',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '国土资源电子政务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 2,
        commonDataMetaName: '危险废物经营许可证',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '国土资源电子政务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 3,
        commonDataMetaName: '辐射安全许可证',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '国土资源电子政务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 4,
        commonDataMetaName: '司法鉴定机构基本信息',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '如法网',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 5,
        commonDataMetaName: '司法鉴定人执业信息',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '全国法律服务机构统一代码管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 6,
        commonDataMetaName: '司法鉴定机构信息',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '如法网',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 7,
        commonDataMetaName: '律师事务所信息-注销信息',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '如法网',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 8,
        commonDataMetaName: '律师事务所信息-变更信息',
        commonDataMetaNameEn: '州环保局',
        commonDataMetaNumber: '如法网',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 9,
        commonDataMetaName: '服刑人员表现查询信息',
        commonDataMetaNameEn: '州司法局',
        commonDataMetaNumber: '刑满释放人员信息管理系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
