export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName: '姓名',
      commonDataMetaNameEn: 'name',
      commonDataMetaNumber: 'xy001',
      commonDataMetaValue: 'xy',
      govStandardDocumentsId: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
      commonDataMetaDescription: '姓名',
      number: 'DB37/T 3433.1',
      version: '2001',
      icsCodeFirst: 'ICS 35.240',
      ccsCodeFirst: 'L 70',
      pubAgency: '省质量技术监督局',
    },
    {
      id: 2,
      commonDataMetaName: '性别',
      commonDataMetaNameEn: 'gender',
      commonDataMetaNumber: 'xy002',
      commonDataMetaValue: 'xy',
      govStandardDocumentsId: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
      commonDataMetaDescription: '性别',
      number: 'DB37/T 3433.1',
      version: '2001',
      icsCodeFirst: 'ICS 35.240',
      ccsCodeFirst: 'L 70',
      pubAgency: '省质量技术监督局',
    },
    {
      id: 3,
      commonDataMetaName: '年龄',
      commonDataMetaNameEn: 'age',
      commonDataMetaNumber: 'xy003',
      commonDataMetaValue: 'xy',
      govStandardDocumentsId: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
      commonDataMetaDescription: '年龄',
      number: 'DB37/T 3433.1',
      version: '2001',
      icsCodeFirst: 'ICS 35.240',
      ccsCodeFirst: 'L 70',
      pubAgency: '省质量技术监督局',
    },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
