export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: 'HZ市公安局机房',
        commonDataMetaNameEn: 'HZ市公安局',
        commonDataMetaNumber: '何益挺',
        commonDataMetaValue: '关键',
        govStandardDocumentsId: '使用中',
      },
      {
        id: 2,
        commonDataMetaName: 'NB市商务局机房',
        commonDataMetaNameEn: 'NB市商务局',
        commonDataMetaNumber: '章佩瑜',
        commonDataMetaValue: '一般',
        govStandardDocumentsId: '已停用',
      }, {
        id: 1,
        commonDataMetaName: 'ZJ省市场监管局机房',
        commonDataMetaNameEn: 'ZJ省市场监管局',
        commonDataMetaNumber: '何益挺',
        commonDataMetaValue: '关键',
        govStandardDocumentsId: '使用中',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省大数据发展管理局机房',
        commonDataMetaNameEn: 'ZJ省大数据发展管理局',
        commonDataMetaNumber: '章佩瑜',
        commonDataMetaValue: '一般',
        govStandardDocumentsId: '已停用',
      }, {
        id: 1,
        commonDataMetaName: 'ZJ省应急管理厅机房',
        commonDataMetaNameEn: 'ZJ省应急管理厅',
        commonDataMetaNumber: '刘家园',
        commonDataMetaValue: '关键',
        govStandardDocumentsId: '使用中',
      },
      {
        id: 2,
        commonDataMetaName: 'ZJ省财政局机房',
        commonDataMetaNameEn: 'ZJ省财政局',
        commonDataMetaNumber: '章佩瑜',
        commonDataMetaValue: '一般',
        govStandardDocumentsId: '已停用',
      }, {
        id: 1,
        commonDataMetaName: 'ZJ省保密局机房',
        commonDataMetaNameEn: 'HZ市公保密局',
        commonDataMetaNumber: '何益挺',
        commonDataMetaValue: '关键',
        govStandardDocumentsId: '使用中',
      },
      {
        id: 2,
        commonDataMetaName: 'NB市安保局机房',
        commonDataMetaNameEn: 'NB市安保局',
        commonDataMetaNumber: '章佩瑜',
        commonDataMetaValue: '一般',
        govStandardDocumentsId: '已停用',
      }, {
        id: 1,
        commonDataMetaName: 'HZ市税务局机房',
        commonDataMetaNameEn: 'HZ市税务局',
        commonDataMetaNumber: '何益挺',
        commonDataMetaValue: '关键',
        govStandardDocumentsId: '使用中',
      },
      {
        id: 2,
        commonDataMetaName: 'NB市商务局机房',
        commonDataMetaNameEn: 'NB市商务局',
        commonDataMetaNumber: '章佩瑜',
        commonDataMetaValue: '一般',
        govStandardDocumentsId: '已停用',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
