export const mockData = {
  code: 0,
  data: {
    records: [{
      id: 1,
      commonDataMetaName: 'A',
      commonDataMetaName1: ' ',
      commonDataMetaName2: ' ',
      commonDataMetaName3: ' ',
      commonDataMetaName4: ' ',
      commonDataMetaName5: '农、林、牧、渔业',
      commonDataMetaName6: '本门类包括01～05大类',
      children: [{
        id: 2,
        commonDataMetaName: ' ',
        commonDataMetaName1: '01',
        commonDataMetaName2: ' ',
        commonDataMetaName3: ' ',
        commonDataMetaName4: ' ',
        commonDataMetaName5: '农业',
        commonDataMetaName6: '指对各种农作物的种植',
        children: [{
          id: 3,
          commonDataMetaName: ' ',
          commonDataMetaName1: ' ',
          commonDataMetaName2: '011',
          commonDataMetaName3: ' ',
          commonDataMetaName4: ' ',
          commonDataMetaName5: '谷物种植',
          commonDataMetaName6: '指以收获籽实为主的农作物的种植，包括稻谷、小麦、玉米等农作物的种植和作为饲料和工业原料的谷物的种植',
          children: [{
            id: 4,
            commonDataMetaName: ' ',
            commonDataMetaName1: ' ',
            commonDataMetaName2: ' ',
            commonDataMetaName3: '0111',
            commonDataMetaName4: ' ',
            commonDataMetaName5: '稻谷种植',
            commonDataMetaName6: ' ',
            children: [{
              id: 5,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '011101',
              commonDataMetaName5: '早籼稻',
              commonDataMetaName6: '种用早籼稻、其他早籼稻',
            }, {
              id: 6,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '011102',
              commonDataMetaName5: '晚籼稻',
              commonDataMetaName6: '种用晚籼稻、其他晚籼稻',
            }, {
              id: 7,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '011103',
              commonDataMetaName5: '中籼稻',
              commonDataMetaName6: '种用中籼稻、其他中籼稻',
            }, {
              id: 8,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '011104',
              commonDataMetaName5: '粳稻',
              commonDataMetaName6: '种用粳稻、其他粳稻',
            }, {
              id: 9,
              commonDataMetaName: ' ',
              commonDataMetaName1: ' ',
              commonDataMetaName2: ' ',
              commonDataMetaName3: ' ',
              commonDataMetaName4: '011105',
              commonDataMetaName5: '其他未列明稻谷。',
              commonDataMetaName6: ' ',
            }],
          }],
        }],
      }],
    }],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
