export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        name: '世界各国和地区名称代码(2000版)',
        number: 'GB/T 2659',
        pubAgency: '国家质量技术监督局',
        proposalUnit: '国家邮政局',
        putunderUnit: '全国信息与文献标准化技术委员会',
        draftingUnit: '国家邮政局科学研究规划院、中国科学技术信息研究所、北京文献服务处',
        classification: '1',
        nature: '1',
        icsCodeFirst: 'ICS 01.040.03',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 24',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '1',
        markWay: '2',
        markCode: 'ISO 3166-1:1997',
        publishTime: '2000-07-31',
        implementationTime: '2001-03-01',
        version: '版本(年代)号',
        repalceVersion: 'GB/T 2659-1994',
      },
      {
        id: 2,
        name: '保险业车联网基础数据元目录(2018版)',
        number: 'JR/T 0165',
        pubAgency: '中国银行保险监督管理委员会',
        proposalUnit: '全国金融标准化技术委员会保险分技术委员会',
        putunderUnit: '全国金融标准化技术委员会保险分技术委员会',
        draftingUnit: '中国人民财产保险股份有限公司、中国保险行业协会、中国平安保险（集团）股份有限公司、中国保险信息技术管理有限责任公司',
        classification: '1',
        nature: '1',
        icsCodeFirst: 'ICS 03.060',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 11',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-07-19',
        implementationTime: '2018-07-19',
        version: '2018版',
        repalceVersion: '',
      },
      {
        id: 3,
        name: '寄递服务人员基础数据元(2018版)',
        number: 'YZ/T 0165',
        pubAgency: '国家邮政局',
        proposalUnit: '国家邮政局',
        putunderUnit: '全国邮政业标准化技术委员会',
        draftingUnit: '国家邮政局发展研究中心',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.040',
        icsCodeSecond: '',
        ccsCodeFirst: 'M 80',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 4,
        name: '商业银行担保物基本信息描述规范 第1部分：通用数据元(2018版)',
        number: 'JR/T 0170.1',
        pubAgency: '中国人民银行',
        proposalUnit: '中国建设银行股份有限公司',
        putunderUnit: '全国金融标准化技术委员会',
        draftingUnit: '中国建设银行股份有限公司、中国银行业协会、中国工商银行股份有限公司、中国农业银行股份有限公司、交通银行股份有限公司、中国邮政储蓄银行股份有限公司',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.240.40',
        icsCodeSecond: '',
        ccsCodeFirst: 'M 80',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 5,
        name: '公共安全管理平台数据规范 第4部分：交换数据项(2019版)',
        number: 'DB3502/T 048.4',
        pubAgency: '市市场监督管理局',
        proposalUnit: '市城市公共安全管理领导小组办公室',
        putunderUnit: '市城市公共安全管理领导小组办公室',
        draftingUnit: '市城市公共安全管理领导小组办公室、市公安局、市美亚柏科信息股份有限公司、厦门畅博思信息技术有限公司、市标准化研究院',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.240.01',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 90',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 6,
        name: '公共安全管理平台数据规范 第3部分：信息代码(2019版)',
        number: 'DB3502/T 048.3',
        pubAgency: '市市场监督管理局',
        proposalUnit: '市城市公共安全管理领导小组办公室',
        putunderUnit: '市城市公共安全管理领导小组办公室',
        draftingUnit: '市城市公共安全管理领导小组办公室、市公安局、市美亚柏科信息股份有限公司、市信息中心、厦门畅博思信息技术有限公司、市标准化研究院',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.240.01',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 90',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 7,
        name: '公共安全管理平台数据规范 第2部分：数据元(2019版)',
        number: 'DB3502/T 048.2',
        pubAgency: '市市场监督管理局',
        proposalUnit: '市城市公共安全管理领导小组办公室',
        putunderUnit: '市城市公共安全管理领导小组办公室',
        draftingUnit: '市城市公共安全管理领导小组办公室、市美亚柏科信息股份有限公司、市公安局、市信息中心、厦门畅博思信息技术有限公司、市标准化研究院',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.240.01',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 90',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 8,
        name: '公共安全管理平台数据规范 第1部分：信息资源分类(2019版)',
        number: 'DB3502/T 048.1',
        pubAgency: '市市场监督管理局',
        proposalUnit: '市城市公共安全管理领导小组办公室',
        putunderUnit: '市城市公共安全管理领导小组办公室',
        draftingUnit: '市城市公共安全管理领导小组办公室、市公安局、市标准化研究院、市信息中心、市美亚柏科信息股份有限公司、厦门畅博思信息技术有限公司',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 35.240.01',
        icsCodeSecond: '',
        ccsCodeFirst: 'A 90',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },
      {
        id: 9,
        name: '供应链安全管理系统 电子口岸通关（EPC） 第2部分：核心数据元(2018版)',
        number: 'GB/T 36147.2',
        pubAgency: '国家市场监督管理总局、中国国家标准化管理',
        proposalUnit: '全国海洋船标准化技术委员会',
        putunderUnit: '全国海洋船标准化技术委员会',
        draftingUnit: '中国船舶工业综合技术经济研究院',
        classification: '2',
        nature: '2',
        icsCodeFirst: 'ICS 47.020.99',
        icsCodeSecond: 'ICS 35.240.60',
        ccsCodeFirst: 'U 07',
        ccsCodeSecond: '',
        udcCode: '',
        isMark: '2',
        publishTime: '2018-11-29',
        implementationTime: '2019-03-01',
        version: '2018版',
        repalceVersion: '',
        remark: '备案号：65890-2019',
      },


    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
