export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        classificationCode: 'ICS 97.220.99',
        classificationName: '其他运动设备和设施',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37/T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 2,
        classificationCode: 'ICS 97.220.40',
        classificationName: '室外和水上运动设备',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37/T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 3,
        classificationCode: 'ICS 97.220.20',
        classificationName: '冬季运动设备',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 4,
        classificationCode: 'ICS 97.220.10',
        classificationName: '运动设施',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 5,
        classificationCode: 'ICS 97.220.30',
        classificationName: '室内运动设备',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 6,
        classificationCode: 'ICS 97.200.99',
        classificationName: '其他文娱活动设备',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 7,
        classificationCode: 'ICS 97.200.50',
        classificationName: '玩具',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 8,
        classificationCode: 'ICS 97.200.40',
        classificationName: '游戏场',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 9,
        classificationCode: 'ICS 97.200.30',
        classificationName: '野营设备和营地',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },
      {
        id: 10,
        classificationCode: 'ICS 97.200.20',
        classificationName: '乐器',
        name: '人口信息管理代码 第5部分 兵役状况代码(2001版)',
        number: 'DB37 / T 3433.1',
        version: '2001',
        icsCodeFirst: 'ICS 35.240',
        ccsCodeFirst: 'L 70',
        pubAgency: '省质量技术监督局',
      },


    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
