export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        commonDataMetaName: '划定（调整）矿区范围申请登记书',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '国土资源电子政务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 2,
        commonDataMetaName: '不动产注销信息',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '不动产登记信息系统',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 3,
        commonDataMetaName: '不动产预告信息',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '不动产登记信息系统',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 4,
        commonDataMetaName: '收集登记湘西州宗教活动场所信息',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '宗教工作基础信息采集系统2014',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 5,
        commonDataMetaName: '收集登记湘西州宗教教职人员信息',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '宗教工作基础信息采集系统2014',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 6,
        commonDataMetaName: '报送民族工作情况（机密除外）',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '国家民委政务信息内网报送系统',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 7,
        commonDataMetaName: '划定（调整）矿区范围申请登记书',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '国土资源电子政务系统',
        commonDataMetaValue: '否',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 8,
        commonDataMetaName: '法律援助统计报表二（人员）',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
      {
        id: 9,
        commonDataMetaName: '法律援助统计报表三（经费投入_省级填报）',
        commonDataMetaNameEn: '州国土局',
        commonDataMetaNumber: '',
        commonDataMetaValue: '是',
        govStandardDocumentsId: '审核通过',
      },
    ],
    total: 3,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
