export const mockData = {
  code: 0,
  data: {
    records: [{
        id: 1,
        deptIdName: "省大数据局",
        matterName: "科技项目评审",
        matterCode: "330101333000",
        auditState: "2",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "118",
      },
      {
        id: 2,
        deptIdName: "省大数据局",
        matterName: "电子认证服务许可",
        matterCode: "330401124000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 3,
        deptIdName: "省应急管理厅",
        matterName: "安全生产领域“黑名单”管理",
        matterCode: "330401124000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 4,
        deptIdName: "省应急管理厅",
        matterName: "公益性民间组织救灾捐赠款分配、使用方案的备案",
        matterCode: "330401124000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 5,
        deptIdName: "省应急管理厅",
        matterName: "危险化学品重大危险源备案、核销",
        matterCode: "330401122000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 6,
        deptIdName: "省应急管理厅",
        matterName: "参与生产安全事故调查",
        matterCode: "330401125000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 7,
        deptIdName: "省应急管理厅",
        matterName: "生产经营单位生产安全事故应急预案备案",
        matterCode: "330401126000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 8,
        deptIdName: "省应急管理厅",
        matterName: "对事故发生单位落实防范和整改措施的情况的监督检查",
        matterCode: "330401127000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 9,
        deptIdName: "省应急管理厅",
        matterName: "对地质勘探单位安全生产的监督检查",
        matterCode: "330401128000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
      {
        id: 10,
        deptIdName: "省应急管理厅",
        matterName: "对安全评价检测检验机构的监督检查",
        matterCode: "330401129000",
        auditState: "3",
        matterType: "1",
        typeKey: ["1", "3"],
        useLevelList: ["1"],
        supCode: "112",
      },
    ],
    total: 2,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData2 = {
  code: 0,
  data: {
    records: [{
      id: 1,
      materialName: '项目技术评审书',
      materialKind: '5',
      hasItem: '1',
      markOrgs: "省大数据局",
      desc: "",
    }],
    total: 1,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};

export const mockData3 = {
  code: 0,
  data: {
    records: [{
      histroyNo: 'V1',
      userName: 'test',
      createTime: '2020-06-12 11:19:10',
    }],
    total: 1,
    size: 10,
    current: 1,
    orders: [],
    searchCount: true,
    pages: 1,
  },
};
