/**
 * ods路由
 * @type { *[] }
 */
const noAuthMeta = {
  keepAlive: false,
  isAuth: false,
};
export default [{
  path: "/ods",
  name: "ODS",
  component: () => import("@/views/ods/index.vue"),
  meta: noAuthMeta,
  children: [
    {
      path: "/ods/wel/:id",
      name: "工作台",
      component: () => import("@/views/ods/pages/wel.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/newPublicData/:id",
      name: "公共数据源池",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/newPublicData/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/standardResources/standardDocument/:id",
      name: "标准文件库",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/standardResources/standardDocument/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/standardResources/standardTerm/:id",
      name: "标准术语库",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/standardResources/standardTerm/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/publicData/:id",
      name: "分类标准",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/publicData/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/standardResources/classCoding/:id",
      name: "分类编码",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/standardResources/classCoding/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/standardModel/modelLibrary/:id",
      name: "模型建库",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/standardModel/modelLibrary/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/dataSupermarket/standardModel/modelDesign/:id",
      name: "模型设计",
      component: () => import("@/views/ods/pages/dataMatrix/dataSupermarket/standardModel/modelDesign/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/standardManage/processAndRules/:id",
      name: "数据流程配置",
      component: () => import("@/views/ods/pages/dataMatrix/standardManage/processAndRules/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataMatrix/standardManage/ruleDesign/:id",
      name: "数据规则设计",
      component: () => import("@/views/ods/pages/dataMatrix/standardManage/ruleDesign/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/qualityEvaluation/testEvaluation/abnormalData/:id",
      name: "实体数据异常监测",
      component: () => import("@/views/ods/pages/dataGovernance/qualityEvaluation/testEvaluation/abnormalData/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/qualityEvaluation/diagnosticReport/:id",
      name: "实体数据异常监测 ",
      component: () => import("@/views/ods/pages/dataGovernance/qualityEvaluation/diagnosticReport/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/qualityPromotion/cleanContrast/cleanPool/:id",
      name: "数据清洗池",
      component: () => import("@/views/ods/pages/dataGovernance/qualityPromotion/cleanContrast/cleanPool/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/qualityPromotion/cleanContrast/waitCleanPool/:id",
      name: "待清洗数据池",
      component: () => import("@/views/ods/pages/dataGovernance/qualityPromotion/cleanContrast/waitCleanPool/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/needComb/specificateData/:id",
      name: "规范事项数据请求",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/needComb/specificateData/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/needComb/generalData/:id",
      name: "通用事项数据请求",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/needComb/generalData/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/needComb/demandResp/:id",
      name: "需求响应",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/needComb/demandResp/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/needComb/withdrawList/:id",
      name: "被撤回清单",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/needComb/withdrawList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/dataResponsible/toBeComfirmed/:id",
      name: "待确认",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/dataResponsible/toBeComfirmed/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/dataResponsible/comfirmed/:id",
      name: "已确认",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/dataResponsible/comfirmed/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/dataResponsible/withdraw/:id",
      name: "撤回待审",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/dataResponsible/withdraw/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/dataFlow/shareDetail/:id",
      name: "共享明细",
      component: () => import("@/views/ods/pages/dataGovernance/dataFlow/shareDetail/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/matter/:id",
      name: "事项目录",
      component: () => import("@/views/ods/pages/application/process/matter/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/material/:id",
      name: "材料目录",
      component: () => import("@/views/ods/pages/application/process/material/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/nationalList/:id",
      name: "国家目录对应",
      component: () => import("@/views/ods/pages/application/process/nationalList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/matterClaim/:id",
      name: "事项认领",
      component: () => import("@/views/ods/pages/application/process/matterClaim/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/listManagement/:id",
      name: "实施清单管理",
      component: () => import("@/views/ods/pages/application/process/listManagement/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/minimumParticleSize/:id",
      name: "最小颗粒度梳理",
      component: () => import("@/views/ods/pages/application/process/minimumParticleSize/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/auditManagement/:id",
      name: "ODS审核管理",
      component: () => import("@/views/ods/pages/application/process/auditManagement/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/theme/design/:id",
      name: "主题设计",
      component: () => import("@/views/ods/pages/application/process/theme/design/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/theme/scene/:id",
      name: "场景应用",
      component: () => import("@/views/ods/pages/application/process/theme/scene/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/policy/guide/:id",
      name: "办事指南",
      component: () => import("@/views/ods/pages/application/process/policy/guide/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/policy/matter/:id",
      name: "申报事项",
      component: () => import("@/views/ods/pages/application/process/policy/matter/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/matterStatistics/matterFill/:id",
      name: "事项填报统计",
      component: () => import("@/views/ods/pages/application/process/matterStatistics/matterFill/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/process/matterStatistics/matterClaim/:id",
      name: "事项认领统计",
      component: () => import("@/views/ods/pages/application/process/matterStatistics/matterClaim/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/accrualDirectory/accrualRegister/:id",
      name: "权责登记",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/accrualDirectory/accrualRegister/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/accrualDirectory/legalBasis/:id",
      name: "法定依据",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/accrualDirectory/legalBasis/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/accrualDirectory/auditManage/:id",
      name: "ODS 审核管理",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/accrualDirectory/auditManage/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/dataResponsibility/requireList/:id",
      name: "需求清单",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/dataResponsibility/requireList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/dataResponsibility/responsibilityList/:id",
      name: "责任清单",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/dataResponsibility/responsibilityList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/dataResponsibility/negativeList/:id",
      name: "负面清单",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/dataResponsibility/negativeList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/wholeManage/resetDept/:id",
      name: "重置责任部门",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/wholeManage/resetDept/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/wholeManage/withdrawAudit/:id",
      name: "责任撤回审核",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/wholeManage/withdrawAudit/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/dataGovernance/accrualSystem/wholeManage/negativeAudit/:id",
      name: "负面清单审核",
      component: () => import("@/views/ods/pages/dataGovernance/accrualSystem/wholeManage/negativeAudit/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/smartCube/knowledgeMap/:id",
      name: "ODS 知识图谱",
      component: () => import("@/views/ods/pages/smartCube/knowledgeMap/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/smartCube/knowledgeMap/:id",
      name: "ODS知识图谱",
      component: () => import("@/views/ods/pages/smartCube/knowledgeMap/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/singleIndex/:id",
      name: "单项指标",
      component: () => import("@/views/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/singleIndex/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/indexSystem/:id",
      name: "指标体系",
      component: () => import("@/views/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/indexSystem/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/manageUpgrades/assessmentAndevaluation/projectEvaluation/:id",
      name: "项目评估",
      component: () => import("@/views/ods/pages/application/manageUpgrades/assessmentAndevaluation/projectEvaluation/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/manageUpgrades/assessmentAndevaluation/assessmentResults/:id",
      name: "考核成果",
      component: () => import("@/views/ods/pages/application/manageUpgrades/assessmentAndevaluation/assessmentResults/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/smartCube/eleSign/:id",
      name: "电子签章(区块链)",
      component: () => import("@/views/ods/pages/smartCube/eleSign/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/smartCube/smartPortrait/:id",
      name: "智能画像(人工智能)",
      component: () => import("@/views/ods/pages/smartCube/smartPortrait/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/smartCube/smartAnalyze/:id",
      name: "智能分析",
      component: () => import("@/views/ods/pages/smartCube/smartAnalyze/index.vue"),
      meta: noAuthMeta,
    },
    // 项目精细 start
    {
      path: "/ods/pages/application/projectLean/projectData/info/:id",
      name: "评审信息",
      component: () => import("@/views/ods/pages/application/projectLean/projectData/projectInfo/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectData/mat/:id",
      name: "项目信息",
      component: () => import("@/views/ods/pages/application/projectLean/projectData/projectInfoStation/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectData/file/:id",
      name: "文档信息",
      component: () => import("@/views/ods/pages/application/projectLean/projectData/projectFile/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectNeed/declare/:id",
      name: "需求申报",
      component: () => import("@/views/ods/pages/application/projectLean/projectNeed/declare/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectNeed/examine/:id",
      name: "需求审核",
      component: () => import("@/views/ods/pages/application/projectLean/projectNeed/examine/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectNeed/back/:id",
      name: "需求退回",
      component: () => import("@/views/ods/pages/application/projectLean/projectNeed/back/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectPlan/declare/:id",
      name: "方案申报",
      component: () => import("@/views/ods/pages/application/projectLean/projectPlan/declare/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectPlan/examine/:id",
      name: "方案审核",
      component: () => import("@/views/ods/pages/application/projectLean/projectPlan/examine/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectPlan/back/:id",
      name: "方案退回",
      component: () => import("@/views/ods/pages/application/projectLean/projectPlan/back/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectFinance/examine/:id",
      name: "审核列表",
      component: () => import("@/views/ods/pages/application/projectLean/projectFinance/examine/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectFinance/back/:id",
      name: "审核退回",
      component: () => import("@/views/ods/pages/application/projectLean/projectFinance/back/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/ods/pages/application/projectLean/projectApproval/upload/:id",
      name: "审批结果上传",
      component: () => import("@/views/ods/pages/application/projectLean/projectApproval/upload/index.vue"),
      meta: noAuthMeta,
    },

    // 项目精细 end
    {
      path: "/ods/pages/smartCube/smartService/question/:id",
      name: "问题库",
      component: () => import("@/views/ods/pages/smartCube/smartService/question/index.vue"),
      meta: noAuthMeta,
    },
  ],
}];
