/**
 * ods路由
 * @type { *[] }
 */
const noAuthMeta = {
  keepAlive: false,
  isAuth: false,
};
export default [{
  path: "/ods",
  name: "ods",
  component: () => import("@/views/ods/index.vue"),
  meta: noAuthMeta,
  children: [
    // 人口基础库
    {
      path: "/dataShare/assetSys/dataAsset/dataManage/population/index/:id",
      name: "人口基础库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/population/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/dataAsset/dataManage/legal/index/:id",
      name: "法人单位基础库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/legal/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/dataAsset/dataManage/credit/index/:id",
      name: "社会信用基础库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/credit/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/dataAsset/dataManage/natural/index/:id",
      name: "自然资源和空间地理库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/natural/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/dataAsset/dataManage/electronic/index/:id",
      name: "电子证照基础库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/electronic/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/policiesRegulations/policies/index/:id",
      name: "政策库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/policiesRegulations/policies/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/policiesRegulations/policy/theme/index/:id",
      name: "政策主题",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/policiesRegulations/policy/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/policiesRegulations/policy/district/index/:id",
      name: "政策适用地区",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/policiesRegulations/district/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/policiesRegulations/policy/industry/index/:id",
      name: "政策适用行业",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataManage/policiesRegulations/industry/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/ruleBase/index/:id",
      name: "规则集",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/ruleBase/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/ruleConfige/index/:id",
      name: "应用规则配置",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/ruleConfige/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/basicDictionary/category/index/:id",
      name: "范畴表",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/basicDictionary/category/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/basicDictionary/categoryCatalogue/index/:id",
      name: "范畴目录",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/basicDictionary/categoryCatalogue/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/basicDictionary/governmentAffairs/index/:id",
      name: "政务主题词",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/basicDictionary/governmentAffairs/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/industryTheme/index/:id",
      name: "行业主题词典",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/industryTheme/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/addressSubject/index/:id",
      name: "地址主题词典",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/addressSubject/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/mechanismDictionary/mechanismBase/index/:id",
      name: "机构库",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/mechanismDictionary/mechanismBase/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataMatrix/dataSupermarket/mechanismDictionary/dutyBase/index/:id",
      name: "机构职责库",
      component: () => import("@/views/ods/pages/dataShare/dataSupermarket/mechanismDictionary/dutyBase/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/infoSystem/index/:id",
      name: "部门信息系统",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/infoSystem/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/infoSystemList/index/:id",
      name: "系统清单",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/infoSystemList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/systemRegister/index/:id",
      name: "系统注册",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/systemRegister/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/libraryRelation/index/:id",
      name: "库目关联",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/libraryRelation/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/libraryManage/index/:id",
      name: "库表管理",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/libraryManage/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/sysCensus/systemReview/index/:id",
      name: "ods_审核管理",
      component: () => import("@/views/ods/pages/dataShare/assetSys/sysCensus/systemReview/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/deptList/index/:id",
      name: "部门目录清单",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/deptList/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/share/index/:id",
      name: "共享目录清单",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/share/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/registration/index/:id",
      name: "目录注册",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/registration/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/fileRes/index/:id",
      name: "文件注册",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/fileRes/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/collection/index/:id",
      name: "归集注册",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/collection/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/interface/index/:id",
      name: "接口注册",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/interface/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/retrieval/index/:id",
      name: "目录检索",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/retrieval/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/examine/index/:id",
      name: "ods审核管理",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataDirectory/examine/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/computeRoom/index/:id",
      name: "ODS机房环境",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/computeRoom/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/software/infSoftware/index/:id",
      name: "应用软件",
      component: () => import("@/views/ods/pages/dataShare/assetSys/software/infSoftware/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/software/infDatabase/index/:id",
      name: "数据库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/software/infDatabase/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/software/infSavant/index/:id",
      name: "中间库",
      component: () => import("@/views/ods/pages/dataShare/assetSys/software/infSavant/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/dataAsset/dataPaper/index/:id",
      name: "其他数据",
      component: () => import("@/views/ods/pages/dataShare/assetSys/dataAsset/dataPaper/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/businessship/index/:id",
      name: "部门业务关系图",
      component: () => import("@/views/ods/pages/dataShare/directorySystem/dataDirectory/businessship/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/directorySystem/dataDirectory/relationship/index/:id",
      name: "部门目录关系图",
      component: () => import("@/views/ods/pages/dataShare/directorySystem/dataDirectory/relationship/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/server/index/:id",
      name: "ods机房环境",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/server/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/VMware/index/:id",
      name: "虚拟机",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/VMware/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/terminal/index/:id",
      name: "终端",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/terminal/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/network/index/:id",
      name: "网络设备",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/network/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/newsletter/index/:id",
      name: "通讯设备",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/newsletter/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/storage/index/:id",
      name: "存储设备",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/storage/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/safe/index/:id",
      name: "安全设备",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/safe/index.vue"),
      meta: noAuthMeta,
    },
    {
      path: "/dataShare/assetSys/hardware/ring/index/:id",
      name: "动环设备",
      component: () => import("@/views/ods/pages/dataShare/assetSys/hardware/ring/index.vue"),
      meta: noAuthMeta,
    },
  ],
}];
