export default [{
  "id": 360701,
  "pid": -1,
  "icon": "icon-guanwangfangwen",
  "name": "赋能应用",
  "spread": false,
  "path": "/dataShare/application",
  "keepAlive": "0",
  "type": "0",
  "label": "赋能应用",
  "sort": 1,
  "children": [{
      "id": 360702,
      "pid": 360701,
      "icon": "icon-guanwangfangwen",
      "name": "流程再造",
      "spread": false,
      "path": "process",
      "keepAlive": "0",
      "type": "0",
      "label": "流程再造",
      "sort": 1,
      "children": [{
          "id": 360703,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "事项目录",
          "spread": false,
          "path": "/ods/pages/application/process/matter",
          "keepAlive": "0",
          "type": "0",
          "label": "事项目录",
          "sort": 1,
        },
        {
          "id": 360704,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "材料清单",
          "spread": false,
          "path": "/ods/pages/application/process/material",
          "keepAlive": "0",
          "type": "0",
          "label": "材料清单",
          "sort": 1,
        },
        {
          "id": 360705,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "国家目录对应",
          "spread": false,
          "path": "/ods/pages/application/process/nationalList",
          "keepAlive": "0",
          "type": "0",
          "label": "国家目录对应",
          "sort": 1,
        },
        {
          "id": 360706,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "事项认领",
          "spread": false,
          "path": "/ods/pages/application/process/matterClaim",
          "keepAlive": "0",
          "type": "0",
          "label": "事项认领",
          "sort": 1,
        },
        {
          "id": 360707,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "实施清单管理",
          "spread": false,
          "path": "/ods/pages/application/process/listManagement",
          "keepAlive": "0",
          "type": "0",
          "label": "实施清单管理",
          "sort": 1,
        },
        {
          "id": 360709,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "最小颗粒度梳理",
          "spread": false,
          "path": "/ods/pages/application/process/minimumParticleSize",
          "keepAlive": "0",
          "type": "0",
          "label": "最小颗粒度梳理",
          "sort": 1,
        },
        {
          "id": 360710,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "审核管理",
          "spread": false,
          "path": "/ods/pages/application/process/auditManagement",
          "keepAlive": "0",
          "type": "0",
          "label": "审核管理",
          "sort": 1,
        },
        {
          "id": 360708,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "事项统计",
          "spread": false,
          "path": "/ods/pages/application/process/matterStatistics",
          "keepAlive": "0",
          "type": "0",
          "label": "事项统计",
          "sort": 1,
          "children": [{
              "id": 360801,
              "pid": 360708,
              "icon": "icon-guanwangfangwen",
              "name": "事项填报统计",
              "spread": false,
              "path": "/ods/pages/application/process/matterStatistics/matterFill",
              "keepAlive": "0",
              "type": "0",
              "label": "事项填报统计",
              "sort": 1,
            },
            {
              "id": 360802,
              "pid": 360708,
              "icon": "icon-guanwangfangwen",
              "name": "事项认领统计",
              "spread": false,
              "path": "/ods/pages/application/process/matterStatistics/matterClaim",
              "keepAlive": "0",
              "type": "0",
              "label": "事项认领统计",
              "sort": 1,
            },
          ],
        },
        {
          "id": 360711,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "政策优汇",
          "spread": false,
          "path": "/ods/pages/application/process/policy",
          "keepAlive": "0",
          "type": "0",
          "label": "政策优汇",
          "sort": 1,
          "children": [{
              "id": 360811,
              "pid": 360711,
              "icon": "icon-guanwangfangwen",
              "name": "申报事项",
              "spread": false,
              "path": "/ods/pages/application/process/policy/matter",
              "keepAlive": "0",
              "type": "0",
              "label": "申报事项",
              "sort": 1,
            },
            {
              "id": 360812,
              "pid": 360711,
              "icon": "icon-guanwangfangwen",
              "name": "办事指南",
              "spread": false,
              "path": "/ods/pages/application/process/policy/guide",
              "keepAlive": "0",
              "type": "0",
              "label": "办事指南",
              "sort": 1,
            },
          ],
        },
        {
          "id": 360712,
          "pid": 360702,
          "icon": "icon-guanwangfangwen",
          "name": "主题服务",
          "spread": false,
          "path": "/ods/pages/application/process/theme",
          "keepAlive": "0",
          "type": "0",
          "label": "主题服务",
          "sort": 1,
          "children": [{
              "id": 360812,
              "pid": 360712,
              "icon": "icon-guanwangfangwen",
              "name": "主题设计",
              "spread": false,
              "path": "/ods/pages/application/process/theme/design",
              "keepAlive": "0",
              "type": "0",
              "label": "主题设计",
              "sort": 1,
            },
            {
              "id": 360813,
              "pid": 360712,
              "icon": "icon-guanwangfangwen",
              "name": "场景应用",
              "spread": false,
              "path": "/ods/pages/application/process/theme/scene",
              "keepAlive": "0",
              "type": "0",
              "label": "场景应用",
              "sort": 1,
            },
          ],
        },
      ],
    },
    {
      "id": 370801,
      "pid": 360701,
      "icon": "icon-guanwangfangwen",
      "name": "管理升级",
      "spread": false,
      "path": "upgrade",
      "keepAlive": "0",
      "type": "0",
      "label": "管理升级",
      "sort": 1,
      "children": [{
          "id": 370703,
          "pid": 370801,
          "icon": "icon-guanwangfangwen",
          "name": "项目精益",
          "spread": false,
          "path": "/ods/pages/application/projectLean",
          "keepAlive": "0",
          "type": "0",
          "label": "项目精益",
          "sort": 1,
          "children": [{
            "id": 370704,
            "pid": 370703,
            "icon": "icon-guanwangfangwen",
            "name": "项目数据",
            "spread": false,
            "path": "/ods/pages/application/projectLean/projectData",
            "keepAlive": "0",
            "type": "0",
            "label": "项目数据",
            "sort": 1,
            "children": [{
              "id": 370705,
              "pid": 370704,
              "icon": "icon-guanwangfangwen",
              "name": "评审信息",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectData/info",
              "keepAlive": "0",
              "type": "0",
              "label": "评审信息",
              "sort": 1,
            }, {
              "id": 370706,
              "pid": 370704,
              "icon": "icon-guanwangfangwen",
              "name": "项目信息",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectData/mat",
              "keepAlive": "0",
              "type": "0",
              "label": "项目信息",
              "sort": 1,
            }, {
              "id": 370707,
              "pid": 370704,
              "icon": "icon-guanwangfangwen",
              "name": "文档信息",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectData/file",
              "keepAlive": "0",
              "type": "0",
              "label": "文档信息",
              "sort": 1,
            }],
          }, {
            "id": 371705,
            "pid": 370703,
            "icon": "icon-guanwangfangwen",
            "name": "项目需求管理",
            "spread": false,
            "path": "/ods/pages/application/projectLean/projectNeed",
            "keepAlive": "0",
            "type": "0",
            "label": "项目需求管理",
            "sort": 1,
            "children": [{
              "id": 371706,
              "pid": 371705,
              "icon": "icon-guanwangfangwen",
              "name": "需求申报",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectNeed/declare",
              "keepAlive": "0",
              "type": "0",
              "label": "需求申报",
              "sort": 1,
            }, {
              "id": 371708,
              "pid": 371705,
              "icon": "icon-guanwangfangwen",
              "name": "需求审核",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectNeed/examine",
              "keepAlive": "0",
              "type": "0",
              "label": "需求审核",
              "sort": 1,
            }, {
              "id": 371707,
              "pid": 371705,
              "icon": "icon-guanwangfangwen",
              "name": "需求退回",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectNeed/back",
              "keepAlive": "0",
              "type": "0",
              "label": "需求退回",
              "sort": 1,
            }],
          }, {
            "id": 372704,
            "pid": 370703,
            "icon": "icon-guanwangfangwen",
            "name": "建设方案管理",
            "spread": false,
            "path": "/ods/pages/application/projectLean/projectPlan",
            "keepAlive": "0",
            "type": "0",
            "label": "建设方案管理",
            "sort": 1,
            "children": [{
              "id": 372705,
              "pid": 372704,
              "icon": "icon-guanwangfangwen",
              "name": "方案申报",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectPlan/declare",
              "keepAlive": "0",
              "type": "0",
              "label": "方案申报",
              "sort": 1,
            }, {
              "id": 372706,
              "pid": 372704,
              "icon": "icon-guanwangfangwen",
              "name": "方案审核",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectPlan/examine",
              "keepAlive": "0",
              "type": "0",
              "label": "方案审核",
              "sort": 1,
            }, {
              "id": 372707,
              "pid": 372704,
              "icon": "icon-guanwangfangwen",
              "name": "方案退回",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectPlan/back",
              "keepAlive": "0",
              "type": "0",
              "label": "方案退回",
              "sort": 1,
            }],
          }, {
            "id": 373704,
            "pid": 370703,
            "icon": "icon-guanwangfangwen",
            "name": "财政费用审核",
            "spread": false,
            "path": "/ods/pages/application/projectLean/projectFinance",
            "keepAlive": "0",
            "type": "0",
            "label": "财政费用审核",
            "sort": 1,
            "children": [{
              "id": 373705,
              "pid": 373704,
              "icon": "icon-guanwangfangwen",
              "name": "审核列表",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectFinance/examine",
              "keepAlive": "0",
              "type": "0",
              "label": "审核列表",
              "sort": 1,
            }, {
              "id": 373706,
              "pid": 373704,
              "icon": "icon-guanwangfangwen",
              "name": "审核退回",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectFinance/back",
              "keepAlive": "0",
              "type": "0",
              "label": "审核退回",
              "sort": 1,
            }],
          }, {
            "id": 374704,
            "pid": 370703,
            "icon": "icon-guanwangfangwen",
            "name": "立项审批",
            "spread": false,
            "path": "/ods/pages/application/projectLean/projectApproval",
            "keepAlive": "0",
            "type": "0",
            "label": "立项审批",
            "sort": 1,
            "children": [{
              "id": 374705,
              "pid": 374704,
              "icon": "icon-guanwangfangwen",
              "name": "审批结果上传",
              "spread": false,
              "path": "/ods/pages/application/projectLean/projectApproval/upload",
              "keepAlive": "0",
              "type": "0",
              "label": "审批结果上传",
              "sort": 1,
            }],
          }],
        },
        {
          "id": 361002,
          "pid": 370801,
          "icon": "icon-guanwangfangwen",
          "name": "考核评估",
          "spread": false,
          "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation",
          "keepAlive": "0",
          "type": "0",
          "label": "考核评估",
          "sort": 4,
          "children": [{
              "id": 361003,
              "pid": 361002,
              "icon": "icon-guanwangfangwen",
              "name": "指标管理",
              "spread": false,
              "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement",
              "keepAlive": "0",
              "type": "0",
              "label": "指标管理",
              "sort": 1,
              "children": [{
                  "id": 361004,
                  "pid": 361003,
                  "icon": "icon-guanwangfangwen",
                  "name": "单项指标",
                  "spread": false,
                  "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/singleIndex",
                  "keepAlive": "0",
                  "type": "0",
                  "label": "单项指标",
                  "sort": 1,
                },
                {
                  "id": 361005,
                  "pid": 361003,
                  "icon": "icon-guanwangfangwen",
                  "name": "指标体系",
                  "spread": false,
                  "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation/indexManagement/indexSystem",
                  "keepAlive": "0",
                  "type": "0",
                  "label": "指标体系",
                  "sort": 2,
                },
              ],
            },
            {
              "id": 361006,
              "pid": 361002,
              "icon": "icon-guanwangfangwen",
              "name": "项目评估",
              "spread": false,
              "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation/projectEvaluation",
              "keepAlive": "0",
              "type": "0",
              "label": "项目评估",
              "sort": 2,
            },
            {
              "id": 361007,
              "pid": 361002,
              "icon": "icon-guanwangfangwen",
              "name": "考核成果",
              "spread": false,
              "path": "/ods/pages/application/manageUpgrades/assessmentAndevaluation/assessmentResults",
              "keepAlive": "0",
              "type": "0",
              "label": "考核成果",
              "sort": 3,
            },
          ],
        },
      ],
    },
  ],
}];
